export enum EffectId {
  FRIENDSHIP_BONUS = 1, // Confirmed
  MOOD_EFFECT = 2, // Confirmed
  SPEED_BONUS = 3,    // c
  STAMINA_BONUS = 4,    // c
  POWER_BONUS = 5, // Confirmed
  GUTS_BONUS = 6,     // c
  WIT_BONUS = 7,    // c
  TRAINING_EFFECTIVENESS = 8, // Confirmed
  INITIAL_SPEED = 9,      // c
  INITIAL_STAMINA = 10,   // c
  INITIAL_POWER = 11,     // c
  INITIAL_GUTS = 12,      // c
  INITIAL_WIT = 13,   // c
  INITIAL_FRIENDSHIP_GAUGE = 14, // Confirmed
  RACE_BONUS = 15,    // c
  FAN_BONUS = 16,     // c
  HINT_LEVELS = 17, // Confirmed
  HINT_FREQUENCY = 18, // Confirmed
  SPECIALTY_PRIORITY = 19, // Confirmed
  EVENT_RECOVERY = 25,    // c
  EVENT_EFFECTIVENESS = 26,   // c
  FAILURE_PROTECTION = 27,    // c
  ENERGY_COST_REDUCTION = 28,   // c
  SKILL_POINT_BONUS = 30,     // c
  WIT_FRIENDSHIP_RECOVERY = 31,   // c
  INITIAL_SKILL_POINTS = 32,      // c
}

export enum UniqEffectId {
  EFFECT_BONUS_DEPENDENT_ON_GAUGE = 101,
  NON_SPEC_TR_EF_DEPENDENT_ON_GAUGE = 102,
  INCREASED_TR_EF_ON_AMOUNT_DIFFERENT_SUP_CARDS_IN_DECK = 103,
  INCREASED_TR_EF_ON_FANS = 104,
  INIT_STAT_FOR_EVERY_CARD_IN_SUPPORT_DECK = 105,
  FRIENDSHIP_BONUS_ON_FRIENDSHIP_TRAININGS = 106,
  FRIENDSHIP_BONUS_BASED_ON_MISSING_ENERGY = 107,
  TR_EF_ON_MAX_ENERGY = 108,      // might be not only tr_ef
  TR_EF_ON_ALL_SUPPORTS_BOND = 109,
  TR_EF_ON_SUPPORTS_ON_SAME_TRAINING = 110,
  TR_EF_ON_TRAINING_FACILITY_LVL = 111,
  CHANCE_TO_REMOVE_FAILURE_CHANCE = 112,
  ENERGY_COST_REDUCTION_WHEN_ON_FRIENDSHIP_TRAINING = 113,
  TR_EF_ON_CURRENT_ENERGY = 114,
  INITIAL_FRIENDSHIP_GAUGE_FOR_ALL_SUPPORTS = 115,
  EFFECT_BONUS_FOR_EVERY_SKILL_OF_CERTAIN_TYPE = 116,
  TR_EF_ON_LEVEL_OF_ALL_TRAINING_FACILITIES = 117,
  EXTRA_TRAINING_LOCATION_ON_BOND = 118,
  SPEC_PRIORITY_FOR_ALL_SUPPORTS_ON_BOND = 119,
  STAT_BONUS_ON_AMOUNT_DIFFERENT_SUP_CARDS_IN_DECK = 120,
  BONUS_BOND_GAIN_FOR_ALL_SUPPORTS = 121,
  EFFECT_BONUS_TO_SUPPORTS_ON_SAME_TRAINING_FOR_NEXT_TURN = 122,
}
