import { z } from 'zod';

const TraineeSkillEvoSchema = z.object({
  old: z.number(),
  new: z.number(),
});

const TraineeItemDataSchema = z.object({
  url_name: z.string(),
  tid: z.string(),
  card_id: z.number(),
  char_id: z.number(),
  name_en: z.string(),
  name_jp: z.string(),
  name_ko: z.string(),
  name_tw: z.string(),
  version: z.string(),
  title: z.string(),
  title_jp: z.string(),
  title_ko: z.string(),
  title_tw: z.string(),
  title_en_gl: z.string(),
  rarity: z.number(),
  costume: z.number(),
  release: z.string(),
  release_ko: z.string().optional(),
  release_zh_tw: z.string().optional(),
  release_en: z.string().optional(),
  obtained: z.string(),
  skills_unique: z.array(z.number()),
  skills_innate: z.array(z.number()),
  skills_evo: z.array(TraineeSkillEvoSchema),
  skills_awakening: z.array(z.number()),
  skills_event: z.array(z.number()),
  stat_bonus: z.array(z.number()),
  talent_group: z.number(),
  base_stats: z.array(z.number()),
  aptitude: z.array(z.string()),
  four_star_stats: z.array(z.number()),
  five_star_stats: z.array(z.number()),
});

const TraineeRaceSchema = z.object({
  id: z.number(),
  name_en: z.string(),
  name_jp: z.string(),
  name_ko: z.string(),
  name_tw: z.string(),
  url_name: z.string().optional(),
  group: z.number(),
  grade: z.number(),
  track: z.number(),
  distance: z.number(),
  terrain: z.number(),
  fans_needed: z.number(),
  fans_gained: z.number(),
  icon_id: z.number(),
});

const TraineeObjectiveSchema = z.object({
  order: z.number(),
  turn: z.number(),
  cond_type: z.number(),
  cond_id: z.number(),
  cond_value: z.number(),
  cond_value_2: z.number(),
  race_type: z.number(),
  target_type: z.number(),
  race_choice: z.number(),
  race_choice_details: z.number(),
  races: z.array(TraineeRaceSchema).optional(),
  turns_break: z.number().optional(),
});

const TraineeCharDataSchema = z.object({
  url_name: z.string(),
  tid: z.string(),
  char_id: z.number(),
  jp_name: z.string(),
  en_name: z.string(),
  name_ko: z.string(),
  name_tw: z.string(),
  playable: z.boolean(),
  playable_ko: z.boolean(),
  playable_zh_tw: z.boolean(),
  playable_en: z.boolean(),
  active: z.boolean(),
  active_ko: z.boolean(),
  active_zh_tw: z.boolean(),
  active_en: z.boolean(),
  va_en: z.string(),
  va_ja: z.string(),
  va_ko: z.string(),
  va_zh_tw: z.string(),
  va_link: z.string(),
  three_sizes: z.object({
    b: z.number(),
    w: z.number(),
    h: z.number(),
  }),
  birth_day: z.number(),
  birth_month: z.number(),
  birth_year: z.number(),
  height: z.number(),
  sex: z.number(),
  race: z.string(),
  rl: z.object({
    country: z.string(),
    death: z.string().optional(),
    races: z.number(),
    wins: z.number(),
    record: z.string(),
    earnings: z.number(),
    active: z.string(),
  }),
});

export const TraineeSchema = z.object({
  isCharCard: z.boolean(),
  itemData: TraineeItemDataSchema,
  objectiveData: z.array(TraineeObjectiveSchema),
  charData: TraineeCharDataSchema,
});

export type TraineeSchemaType = z.infer<typeof TraineeSchema>;
