import { EffectId } from '../interfaces/effect-id.enum';

export const effectMap: Record<EffectId, { short: string; long: string; }> = {
  [EffectId.FRIENDSHIP_BONUS]: { short: 'FRD', long: 'Friendship Bonus' },
  [EffectId.MOOD_EFFECT]: { short: 'MOOD', long: 'Mood Effect' },
  [EffectId.SPEED_BONUS]: { short: '+SPD', long: 'Speed Bonus' },
  [EffectId.STAMINA_BONUS]: { short: '+STA', long: 'Stamina Bonus' },
  [EffectId.POWER_BONUS]: { short: '+PWR', long: 'Power Bonus' },
  [EffectId.GUTS_BONUS]: { short: '+GUT', long: 'Guts Bonus' },
  [EffectId.WIT_BONUS]: { short: '+WIT', long: 'Wit Bonus' },
  [EffectId.TRAINING_EFFECTIVENESS]: { short: 'TR EF', long: 'Training Effectiveness' },
  [EffectId.INITIAL_SPEED]: { short: 'INIT SPD', long: 'Initial Speed' },
  [EffectId.INITIAL_STAMINA]: { short: 'INIT STA', long: 'Initial Stamina' },
  [EffectId.INITIAL_POWER]: { short: 'INIT PWR', long: 'Initial Power' },
  [EffectId.INITIAL_GUTS]: { short: 'INIT GUT', long: 'Initial Guts' },
  [EffectId.INITIAL_WIT]: { short: 'INIT WIT', long: 'Initial Wit' },
  [EffectId.INITIAL_FRIENDSHIP_GAUGE]: { short: 'INIT FRD', long: 'Initial Friendship Gauge' },
  [EffectId.RACE_BONUS]: { short: 'RACE', long: 'Race Bonus' },
  [EffectId.FAN_BONUS]: { short: 'FAN', long: 'Fan Bonus' },
  [EffectId.HINT_LEVELS]: { short: 'HNT LV', long: 'Hint Levels' },
  [EffectId.HINT_FREQUENCY]: { short: 'HNT FR', long: 'Hint Frequency' },
  [EffectId.SPECIALTY_PRIORITY]: { short: 'SPEC', long: 'Specialty Priority' },
  [EffectId.EVENT_RECOVERY]: { short: 'EVT REC', long: 'Event Recovery' },
  [EffectId.EVENT_EFFECTIVENESS]: { short: 'EVT EFF', long: 'Event Effectiveness' },
  [EffectId.FAILURE_PROTECTION]: { short: 'FAIL PROT', long: 'Failure Protection' },
  [EffectId.ENERGY_COST_REDUCTION]: { short: 'NRG CST', long: 'Energy Cost Reduction' },
  [EffectId.SKILL_POINT_BONUS]: { short: '+SP', long: 'Skill Point Bonus' },
  [EffectId.WIT_FRIENDSHIP_RECOVERY]: { short: 'WIT REC', long: 'Wit Friendship Recovery' },
  [EffectId.INITIAL_SKILL_POINTS]: { short: 'INIT SP', long: 'Initial Skill Points' },
};
